<h1>About</h1>
<hr/>
<h2>Description</h2>
<p>This application was created as a project on Junior Java Developer course in infoShare academy.</p>
<h2>Team</h2>
<ul>
    <li>Byczkowski Dawid</li>
    <li>Jackiewicz Karol</li>
    <li>Matosek Michał</li>
    <li>Watus Jakub</li>
</ul>
<h2>Technology</h2>
<ul>
    <li>Java</li>
    <li>JavaEE</li>
    <li>MySQL</li>
    <li>Freemarker</li>
    <li>Gson</li>
    <li>...</li>
</ul>

