<h1>${title}</h1>
<hr/>

<div class="col-3">
    <form method="get" action="/find-the-closest-by-address" >
        <fieldset>
            <div class="form-group">
              <label for="town">Address</label>
              <input type="text" name="address" class="form-control" placeholder="Enter address">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </fieldset>
    </form>
</div>
